import { PDFDocument } from 'pdf-lib';

/**
 * Perform a deep forensic audit on a bank statement PDF.
 * @param {File | Uint8Array} fileData - The raw PDF data.
 * @param {Array<Array<string>>} transactions - The parsed transaction rows.
 */
export async function auditStatement(fileData, transactions) {
  const results = {
    riskRating: 'Low',
    riskScore: 0,
    anomalies: [],
    metadata: {},
    mathAudit: {
      passed: true,
      failedRows: []
    }
  };

  // 1. Metadata & Structural Audit
  try {
    const rawBuffer = fileData instanceof Uint8Array ? fileData : await fileData.arrayBuffer();
    const pdfDoc = await PDFDocument.load(rawBuffer, { ignoreEncryption: true });
    
    results.metadata = {
      creator: pdfDoc.getCreator() || 'Unknown',
      producer: pdfDoc.getProducer() || 'Unknown',
      created: pdfDoc.getCreationDate()?.toISOString() || 'Unknown',
      modified: pdfDoc.getModificationDate()?.toISOString() || 'Unknown',
    };

    // Structural Flag: Non-Bank Creators
    const suspiciousCreators = ['word', 'canva', 'preview', 'acrobat', 'nitro', 'pdfexpert', 'ilovepdf', 'smallpdf'];
    const creator = results.metadata.creator.toLowerCase();
    const producer = results.metadata.producer.toLowerCase();
    
    if (suspiciousCreators.some(c => creator.includes(c) || producer.includes(c))) {
      results.anomalies.push({
        type: 'Suspicious Software',
        severity: 'Medium',
        message: `Document was generated or modified using a retail editor (${results.metadata.creator}). Bank-grade statements are usually generated by high-volume mainframe systems.`
      });
      results.riskScore += 30;
    }

    // Structural Flag: Incremental Saves
    // We scan the raw bytes for multiple %%EOF markers.
    // Multiple markers usually indicate the file was "Quick Saved" after an edit.
    const decoder = new TextDecoder();
    const rawText = decoder.decode(rawBuffer.slice(-2048)); // check the end of the file
    const eofMarkers = (rawText.match(/%%EOF/g) || []).length;
    // For more accuracy, we search the whole buffer for large files
    const fullText = decoder.decode(rawBuffer);
    const fullEofCount = (fullText.match(/%%EOF/g) || []).length;

    if (fullEofCount > 1) {
      results.anomalies.push({
        type: 'Incremental Save Detected',
        severity: 'High',
        message: 'This PDF has been saved multiple times. Original bank statements are typically single-write documents. This is a common indicator of manual editing.'
      });
      results.riskScore += 50;
    }
  } catch (err) {
    console.error("Forensic Meta Audit Error:", err);
  }

  // 2. Mathematical Audit
  // This requires identifying columns for Date, Amount, and Balance.
  // We'll use a simplified version of the parser's logic to find these.
  const auditResults = validateRunningBalance(transactions);
  results.mathAudit = auditResults;
  
  if (!auditResults.passed) {
    results.anomalies.push({
      type: 'Mathematical Mismatch',
      severity: 'Critical',
      message: `Found ${auditResults.failedRows.length} lines where the running balance does not match transaction totals. This is a primary indicator of manual forgery.`
    });
    results.riskScore += 60;
  }

  // 3. Final Risk Calculation
  if (results.riskScore >= 80) results.riskRating = 'High';
  else if (results.riskScore >= 30) results.riskRating = 'Medium';
  else results.riskRating = 'Low';

  return results;
}

/**
 * Validates the running balance across transaction rows.
 */
function validateRunningBalance(rows) {
  const failedRows = [];
  
  // Heuristic to find Balance and Amount columns
  // Assuming the parser has already cleaned the rows.
  // We look for col indices that reliably contain numbers.
  
  if (rows.length < 2) return { passed: true, failedRows: [] };

  const sampleRow = rows[0];
  let amountCol = -1;
  let balanceCol = -1;

  // Find columns that are strictly numeric (amounts)
  const numericColIndices = [];
  sampleRow.forEach((cell, i) => {
    if (isNumeric(cell)) numericColIndices.push(i);
  });

  if (numericColIndices.length < 1) return { passed: true, failedRows: [] };

  // Heuristic: Balance is usually the LAST numerical column.
  // Amount is usually the first or second numerical column.
  balanceCol = numericColIndices[numericColIndices.length - 1];
  amountCol = numericColIndices[0];

  // If there's only one numeric column, we can't check running balance 
  // unless we have specific info, so we skip.
  if (amountCol === balanceCol) return { passed: true, failedRows: [] };

  for (let i = 1; i < rows.length; i++) {
    const prevBalance = cleanNum(rows[i-1][balanceCol]);
    const currentAmount = cleanNum(rows[i][amountCol]);
    const currentBalance = cleanNum(rows[i][balanceCol]);

    if (prevBalance === null || currentAmount === null || currentBalance === null) continue;

    // Check: PrevBal + Amount = CurrBal
    // We use a small epsilon for floating point math
    const expectedBalance = prevBalance + currentAmount;
    const diff = Math.abs(expectedBalance - currentBalance);

    if (diff > 0.01) {
      failedRows.push({
        index: i,
        expected: expectedBalance.toFixed(2),
        actual: currentBalance.toFixed(2),
        diff: diff.toFixed(2),
        rowData: rows[i]
      });
    }
  }

  return {
    passed: failedRows.length === 0,
    failedRows
  };
}

function isNumeric(val) {
  if (!val) return false;
  const clean = val.replace(/[$,\s]/g, '');
  return !isNaN(parseFloat(clean)) && isFinite(clean);
}

function cleanNum(val) {
  if (!val) return null;
  const clean = val.replace(/[$,\s]/g, '');
  const num = parseFloat(clean);
  return isNaN(num) ? null : num;
}
